### ISSUE TITLE
multi-zone simulation

### ISSUE THREAD

**Issue by MatthiVH** [IWUGERMANY/DIBS---Dynamic-ISO-Building-Simulator#1]
Hi,

I was wondering if the python model can be used for a multi-zone hourly simulation as well (and if you have an example of this, e.g. with 2 zones)?

Best,
Matthias

**Comment by julianbischof** [comment]
Hi Matthias,

Sorry for the late answer. Somehow I missed that issue ;D. To your Question: The DIBS was and is developed to allow "accurate" building simulation with a minimum of effort allowing the use of typically available building stocd data. Therefore I implemented only a one-zone model. 

All the best,
Julian
