### ISSUE TITLE
Appliance_gains_elt_demand_sum is not being appended to a list

### ISSUE THREAD

**Issue by ketuncay** [IWUGERMANY/DIBS---Dynamic-ISO-Building-Simulator#8]
Ich habe ein Problem entdeckt, als ich DIBS zur Simulation der Solarstromerzeugung in den Gebäuden verwendet habe. Appliance_gains_elt_demand wird nicht an eine Liste angehängt, sondern im hourlyResults-Datenrahmen gespeichert und später summiert, um den Jahreswert zu erhalten. Dieser Jahreswert wird später zur Berechnung des Strombedarfs verwendet. Leider wird im Datenrahmen immer derselbe Wert gespeichert, da der Parameter nicht an die Liste angehängt wird. Infolgedessen ist Appliance_gains_elt_demand das ganze Jahr über konstant und der Gesamtstrombedarf ergibt einen falschen Wert. Ich habe dieses Problem behoben, indem ich Appliance_gains_elt_demand einfach an eine Liste angehängt habe. Zu Ihrer Information...

hourlyResults = pd.DataFrame({
        'ApplianceGainsEltDemand':ApplianceGainsEltDemand,
        'HeatingDemand': HeatingDemand,
        'HeatingEnergy': HeatingEnergy,
        'Heating_Sys_Electricity': Heating_Sys_Electricity,
        'Heating_Sys_Fossils': Heating_Sys_Fossils,
        'CoolingDemand': CoolingDemand,
        'CoolingEnergy': CoolingEnergy,
        'Cooling_Sys_Electricity': Cooling_Sys_Electricity,
        'Cooling_Sys_Fossils': Cooling_Sys_Fossils,
        'HotWaterDemand': HotWaterDemand, 
        'HotWaterEnergy': HotWaterEnergy, 
        'HotWater_Sys_Electricity': HotWater_Sys_Electricity, 
        'HotWater_Sys_Fossils': HotWater_Sys_Fossils, 
        'IndoorAirTemperature': TempAir,
        'OutsideTemperature':  OutsideTemp,
        'LightingDemand': LightingDemand,
        'InternalGains': InternalGains,
        'Appliance_gains_demand': Appliance_gains_demand,
        'Appliance_gains_elt_demand': Appliance_gains_elt_demand,
        'SolarGainsSouthWindow': SolarGainsSouthWindow,
        'SolarGainsEastWindow': SolarGainsEastWindow,
        'SolarGainsWestWindow': SolarGainsWestWindow,
        'SolarGainsNorthWindow': SolarGainsNorthWindow,
        'SolarGainsTotal': SolarGainsTotal,
        'Daytime': DayTime, 
        })

**Comment by AndreM84** [comment]
Hallo ketuncay,

danke für die Info zum Verhalten von "Appliance_gains_elt_demand".
Das Problem sollte m. W. mit dem Commit im Dezember 2023 bereits behoben sein:

> Update annualSimulation.py
> [julianbischof](https://github.com/julianbischof)pushed 1 commit • dd0c9b1…56e5179 • on 15. Dez. 2023

Bitte prüfe, welchen Stand du für deine Berechnungen und Anpassungen verwendet hast.

**Comment by julianbischof** [comment]
Vielen Dank für den Hinweis, aber wie bereits angemerkt wurde genau dieses Problem im Dezember 2023 bereits behoben:

![grafik](https://github.com/IWUGERMANY/DIBS---Dynamic-ISO-Building-Simulator/assets/30439298/70a6dc58-4e44-4d9e-8e98-b3f4ca5b1074)

"Corrected Bug in writing hourly results of Appliance_gains_demands and Appliance_gains_elt_demands. The calculation of both was and is correct in DIBS, but the values were saved incorrectly, resulting in the last-hour value being written in all hours and summed up to the annual values. Consequently, the Appliance_gains_demand_sum and Appliance_gains_elt_demand_sum were wrong in the Excel outputs. This is fixed now. The Bug did not affect any other output results, as the calculation was and is performing correctly."

**Comment by julianbischof** [comment]
The issue was already solved in December 2023.
